#Nazwa pliku zapisującego aktywne wypożyczenia w trybie lokalnym
active_hires_file_name: active.json
#Nazwa pliku zapisującego historię wypożyczeń w trybie lokalnym
history_file_name: history.json
#Format w jakim zapisywana jest data wypożyczenia lub zwrotu książki itp.
date_format: '%d.%m.%Y'
#
mongodb_connection_string:
mongo_rents_db_name:
mongo_users_db: Users
mongo_users_collection: users
active_rents_collection_name: activeRents
history_rents_collection_name: historyRents
#Email, z którego będziesz wysyłać emaile z kodem potwierdzającym, zmianą hasła itp.
sender_email:
#Emaile administratorów
admins_emails:
    - example@example.com
#Program wysyła emaile przez serwery Gmail dlate
sender_password:

viewer_role_name: viewer
librarian_role_name: librarian
admin_role_name: admin

keycloak:
    server_url: 'https://example/auth/'
    realm_name: 
    openID:
        client_id:
        client_secret: ''

    admin:
        username:
        password: