name: Change target database

on:
  workflow_dispatch:

jobs:
  change-db-target-to-Prymus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update database client
        run: sed -i 's/db = client.Testing/db = client.Prymus/' main.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Change target database"
          git push
