name: Change target database to Testing

on:
  create:
    branches:
      - develop*

jobs:
  change-db-target-to-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update database client
        run: sed -i 's/db = client.Prymus/db = client.Testing/' main.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Change target database to Testing"
          git push
